services:
  - type: web
    name: my-messenger
    env: node
    buildCommand: npm install && npm run setup
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /health
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1